# Generated by Django 4.2.4 on 2024-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getintouch', '0002_remove_contactmessage_message_contactmessage_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='project_type',
            field=models.CharField(choices=[('web_design', 'Web Design'), ('mobile_app', 'Mobile App'), ('graphic_design', 'Graphic Design'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
